#!/bin/bash

# Get a list of all running containers
containers=$(docker ps -aq)

# Loop through the list of containers and update them
for container in $containers
do
  # Stop the container
  docker stop $container

  # Get the image associated with the container
  image=$(docker inspect --format='{{.Config.Image}}' $container)

  # Pull the latest version of the image
  docker pull $image

  # Start the container using the updated image
  docker start $container
done
